authors:
  - Alex Willmer <alex@moreati.org.uk>
description:
  Manage processes with psutil
namespace: moreati
name: psutil
readme: README.md
license:
  - Apache-2.0
repository: https://github.com/moreati/psutil-ansible
tags:
  - process
  - ps
  - psutil
version: 0.1.0
