- name: Exercise psutil
  hosts: localhost
  gather_facts: false
  tasks:
    - shell:
        cmd: |
          echo $$
          sleep 20 &
          echo $!
      register: sleepers

    - debug:
        var: sleepers

    - psutil_kill:
        pids: "{{ sleepers.stdout_lines }}"
      register: killers
